### PR TITLE
Update readme files

### PR DESCRIPTION
**Pull request by gtrevisan**
- modify contributing guide,
- add badges to readme,
- add security policy,
- [x] fully revamp the readme -- @crea-psfc,
- [x] other rough pass at the docs -- @amdecker.

preview: https://github.com/MIT-PSFC/disruption-py/blob/update-readmes/README.md

### CODE REVIEW

**Comment by amdecker** [comment]
Given the readme mentions SPARC, I'll add that at CFS there's encouragement to use the word "device" or "machine" (and later, hopefully, "power plant") instead of "reactor" to have a strong differentiation between fusion projects and fission projects. 
https://github.com/MIT-PSFC/disruption-py/blob/74d4c150eae0083895f38253d741a12caf61cb8c/README.md?plain=1#L29

**Comment by gtrevisan** [comment]
@amdecker how should we solve the duplicated information between `README.md` and `docs/index.md`? copy/paste?
(actually, IMHO we should use the mkdocs webpage with caution for now -- eg for automated API documentation and any technical Q&A...)

**Comment by amdecker** [comment]
> @amdecker how should we solve the duplicated information between `README.md` and `docs/index.md`? copy/paste? (actually, IMHO we should use the mkdocs webpage with caution for now -- eg for automated API documentation and any technical Q&A...)

One idea would be we could add this to our docs/index.md  `--8<-- "README.md"` which would insert the contents of the readme file into the docs. If we do that, we would need to change a few of the relative links to be absolute.

**Comment by gtrevisan** [comment]
@amdecker is this good to go wrt the docs?

**Review by crea-psfc — APPROVED** [review]
changes look good to me, we can merge @gtrevisan

**Pull request merged**
